run:
  name: model_1
  runs_dir: ./runs
train:
  epochs: 1
model:
  backbone: microsoft/mdeberta-v3-base
data:
  batch_size: 32
logging:
  wandb:
    enable: true
    save_ckpt: 0
  loss_steps: 1
  valid_steps: 500
  ckpt_steps: 5000
