_wandb:
    value:
        cli_version: 0.23.1
        e:
            pcac6i6ow62tr03l0b1ht5pqwqbykf65:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "51539607552"
                args:
                    - --config
                    - configs/train.yml
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "512459501568"
                email: loganbrenningmeyer@gmail.com
                executable: /opt/miniconda3/envs/binaryalign/bin/python
                git:
                    commit: a3355a7d4897265add0b8253bf58dcf665977f29
                    remote: https://github.com/loganbrenningmeyer/binaryalign.git
                host: Logans-MacBook-Pro-2.local
                memory:
                    total: "51539607552"
                os: macOS-26.1-arm64-arm-64bit
                program: -m binaryalign.train
                python: CPython 3.10.19
                root: /Users/loganbrenningmeyer/Documents/GitHub/binaryalign
                startedAt: "2026-01-05T08:45:08.436552Z"
                writerId: pcac6i6ow62tr03l0b1ht5pqwqbykf65
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 13
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": darwin-arm64
