# ====================
# Run Configuration
# ====================
run:
  name: french_1
  runs_dir: ./runs
  resume:
    enable: 1
    ckpt_name: "model-pretrain-step25000.ckpt"

# ====================
# Training Parameters
# ====================
train:
  pretrain:
    steps: 100000
    lr: 0.00002 #2e-5
  finetune:
    steps: 10000
    lr: 0.000004 #4e-6 = 2e-5 / 5


# ====================
# Model Configuration
# ====================
model:
  backbone: microsoft/mdeberta-v3-base
  max_length: 256

# ====================
# Dataset Configuration
# ====================
data:
  finetune:
    src_lang: en
    tgt_lang: fr
  manifest_path: ./datasets/processed/manifest.json
  batch_size: 8
  alpha: 0.5

# ====================
# Logging Configuration
# ====================
logging:

  wandb:
    enable: true
    save_ckpt: 0

  loss_steps: 1
  valid_steps: 500

  ckpt_steps:
    pretrain: 25000
    finetune: 2500
